# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lcmnew.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(560, 320)
        MainWindow.setMinimumSize(QtCore.QSize(560, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("AIIMS Logo 32X32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)

        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 0, 0 , 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 0, 1 , 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0 , 6, 1, 1)
        
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setMaximumSize(QtCore.QSize(60, 16777215))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)

        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)

        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)

        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)

        self.gridLayout.addWidget(self.listWidget, 2, 0, 1, 1)
        self.listWidget_2 = QtGui.QListWidget(self.centralwidget)
        self.listWidget_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)

        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)

        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)

        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        
        self.gridLayout.addWidget(self.listWidget_2, 2, 2, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 5)

        #self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        #self.textBrowser.setMaximumSize(QtCore.QSize(16777215,50))
        #self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        #self.gridLayout.addWidget(self.textBrowser, 0, 6, 1, 1)
        
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        #self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        #self.graphicsView.setStyleSheet(_fromUtf8(""))
        #self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        #self.gridLayout.addWidget(self.graphicsView, 2, 4, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 1, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionStart.setShortcut("Ctrl+W")
        self.actionStart.setStatusTip('Start')
        self.actionStart.triggered.connect(self.startgraph)

        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
 
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionExit.setShortcut("Ctrl+Q")
        self.actionExit.setStatusTip('Exit')
        self.actionExit.triggered.connect(self.close)
        
        self.action1_Graph = QtGui.QAction(MainWindow)
        self.action1_Graph.setObjectName(_fromUtf8("action1_Graph"))
        self.action2_Graph = QtGui.QAction(MainWindow)
        self.action2_Graph.setObjectName(_fromUtf8("action2_Graph"))
        self.actionAuthor = QtGui.QAction(MainWindow)
        self.actionAuthor.setObjectName(_fromUtf8("actionAuthor"))
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionStop = QtGui.QAction(MainWindow)
                
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionStop)
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.action1_Graph)
        self.menuView.addAction(self.action2_Graph)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionInfo)
        self.menuAbout.addAction(self.actionAuthor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Lungs Compliance Meter", None))
        self.label_3.setText(_translate("MainWindow", "Pleural Pressure (in cmH20)", None))
        self.label_4.setText(_translate("MainWindow", "Volume\n(in mL)", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(19)        
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget.item(20)
        
        self.listWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(3)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(4)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(5)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(6)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(7)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(8)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(9)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(10)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(11)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(12)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(13)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(14)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(15)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(16)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(17)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(18)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(19)
        item.setText(_translate("MainWindow", " ", None))
        item = self.listWidget_2.item(20) 
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>outputs!</p></body></html>", None))
        self.label.setText(_translate("MainWindow", "Pressure(cmH2O)", None))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>outputs!</p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "Volume(mL)", None))

        self.pushButton_2.setText(_translate("MainWindow", "Stop", None))
        self.pushButton_2.setStyleSheet("background-color: red")
        self.pushButton_2.clicked.connect(self.stopgraph)
        
        self.pushButton.setText(_translate("MainWindow", "Start", None))
        self.pushButton.setStyleSheet("background-color: green")
        self.pushButton.clicked.connect(self.startgraph)
        
        self.comboBox.setItemText(0, _translate("MainWindow", "Static Compliance", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Dynamic Compliance", None))
        #self.comboBox.setItemText(2, _translate("MainWindow", "Compliance Curve", None))
        self.comboBox.currentIndexChanged.connect(self.comboboxvalue)

        self.checkBox.setText(_translate("MainWindow", "Static Volume-Pressure", None))
        self.checkBox.stateChanged.connect(lambda:self.setpointsstatic(self.checkBox))
        self.checkBox_2.setText(_translate("MainWindow", "Dynamic Volume-Pressure", None))
        self.checkBox_2.stateChanged.connect(lambda:self.setpointsdynamic(self.checkBox_2))
        
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionStart.setText(_translate("MainWindow", "Start", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionStop.setShortcut("Ctrl+E")
        self.actionStop.setStatusTip('Stop')
        self.actionStop.triggered.connect(self.stopgraph)
        
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.action1_Graph.setText(_translate("MainWindow", "Static Compliance", None))
        self.action1_Graph.setStatusTip('Static Compliance')
        self.action1_Graph.triggered.connect(self.staticcompliance)
        
        self.action2_Graph.setText(_translate("MainWindow", "Dynamic Compliance", None))
        self.action2_Graph.setStatusTip('Expiration Graph')
        self.action2_Graph.triggered.connect(self.dynamiccompliance)
        
        
        self.actionAuthor.setText(_translate("MainWindow", "Developer", None))
        self.actionAuthor.setStatusTip('Developer Info')
        self.actionAuthor.triggered.connect(self.devinfo)
        
        self.actionInfo.setText(_translate("MainWindow", "Info", None))
        self.actionInfo.setStatusTip('Software Info')
        self.actionInfo.triggered.connect(self.info)

        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionHelp.setStatusTip('Help')
        self.actionHelp.triggered.connect(self.help)

    def close(self):
        sys.exit()
        
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

